#
# You can use artifacts to pass data to jobs in later stages.
# For more information, see https://docs.gitlab.com/ee/ci/pipelines/job_artifacts.html
#

stages:
  - build

build-job:
  stage: build
  script:
    - yarn build
